name: Generate and Publish Blog

on:
  schedule:
    - cron: '0 12 * * *' # Runs every day at 12:00 UTC
  workflow_dispatch: # Allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install openai

      - name: Run Post Generator
        run: python auto_post_generator.py

      - name: Commit and Push Post
        run: |
          git config user.name "AutoPosterBot"
          git config user.email "autobot@example.com"
          git add posts/
          git commit -m "Auto-post: Added blog post for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin main
