name: Generate and Publish Blog

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # runs daily at 12:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install openai
      - name: Run Post Generator
        run: python3 auto_post_generator.py
